const VERSION='1.1.0', KEY='nirc-marathon-schedule-data';
const $=id=>document.getElementById(id); const DAY=['월','화','수','목','금','토','일'];
const TRAININGS=['휴식','완전 휴식','조깅','회복 조깅','E Easy Run','보강','스트라이드','300m / 100m 인터벌','400m / 200m 인터벌','800m 인터벌','1000m / 200m 인터벌','1000m × 4','1600m × 3','2000m × 3','3000m × 3 크루즈','3000m × 4 크루즈','3000m × 5 크루즈','2000m × 5 크루즈','1600m × 6 크루즈','3000m / 2000m / 1000m 복합','400m × 10','1000m × 5','1600m × 5','피라미드 400-800-1200-1600-1200-800-400','400/400 변속주','12km 빌드업','20km 빌드업','25분주 + 1600m','5000m TT','10K TT','MP Run','MP + 10초','E-LONG','AR LONG','PROGRESSIVE','MP FINISH','MP BLOCK','RACE SIMULATION','24~26km Progressive + MP Finish','Half 21.1km 통제주','12~14km Easy + MP 1~2km','5K BLOCK','35km Simulation (10km E + 25km MP)','하프 대회','JACK DANIELS (E3.2k + T1200/E2분×4 + E3.2k)','FULL MARATHON','직접 입력'];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{race:{},weeks:{}}; let current=1, view='all', currentMonth=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function secFmt(s){s=Math.round(s);let h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`}
function paceFmt(s){return secFmt(s)+'/km'} function range(a,b){return `${paceFmt(a)} ~ ${paceFmt(b)}`}
function vdotFor(d,s){let t=s/60,v=d/t,vo=-4.60+.182258*v+.000104*v*v,p=.8+.1894393*Math.exp(-.012778*t)+.2989558*Math.exp(-.1932605*t);return vo/p} function timeForVdot(d,target){let lo=30,hi=600;for(let i=0;i<80;i++){let mid=(lo+hi)/2,val=vdotFor(d,mid*60);if(val>target)lo=mid;else hi=mid}return(lo+hi)/2*60}
function paceFromVO2(vo){let a=.000104,b=.182258,c=-(4.60+vo),v=(-b+Math.sqrt(b*b-4*a*c))/(2*a);return 60000/v} function parse10(v){v=(v||'').replace(/\D/g,'');if(v.length<3)return 0;let m=+v.slice(0,-2),s=+v.slice(-2);if(s>59)return 0;return m*60+s} function parseFull(v){let x=(v||'').replace(/\D/g,'');if(!x)return 0;if(x.length<=4){let m=+x.slice(0,-2),s=+x.slice(-2);return m*60+s}let h=+x.slice(0,-4),m=+x.slice(-4,-2),s=+x.slice(-2);return h*3600+m*60+s}
function myFormula(ten,sex){let add=ten<=2400?480:ten<=3000?540:600,half=ten*2+add;return half*2+(sex==='female'?600:780)}
function calculate(){let ten=parse10($('tenk').value);if(!ten){alert('10K PB를 4000처럼 입력해주세요.');return}let sex=$('sex').value,vd=vdotFor(10000,ten),vf=timeForVdot(42195,vd),mf=myFormula(ten,sex),avg=(vf+mf)/2,k=ten/10,mPace=vf/42.195,t=paceFromVO2(vd*.88),eFast=paceFromVO2(vd*.74),eSlow=paceFromVO2(vd*.59),goal=parseFull($('goalFull').value);state.race={name:$('raceName').value||'마라톤 대회',date:$('raceDate').value,sex,ten,weekCount:+$('weeks').value,goal,vd,vf,mf,avg,k,mPace,t,eFast,eSlow};save();renderMetrics();buildWeekSelect();renderWeek();renderSchedule()}
function renderMetrics(){let r=state.race;if(!r.vd){$('metrics').innerHTML='';return}let goal=r.goal||r.avg;$('metrics').innerHTML=[['10K 평균 K',paceFmt(r.k)],['VDOT',r.vd.toFixed(1)],['VDOT 풀 예상',secFmt(r.vf)],['나의 공식 풀 예상',secFmt(r.mf)],['평균 풀 예상',secFmt(r.avg)],['VDOT M Pace',paceFmt(r.mPace)],['T Pace',paceFmt(r.t)],['E Pace',secFmt(r.eSlow)+' ~ '+paceFmt(r.eFast)],['목표 FULL',r.goal?secFmt(r.goal):'미입력'],['D-2 Half 기준',secFmt(goal/2-50)]].map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function mondayOfWeek(n){let r=state.race;if(!r.date)return null;let d=new Date(r.date+'T12:00:00'),dow=(d.getDay()+6)%7,mon=new Date(d);mon.setDate(d.getDate()-dow-7*n);return mon} function fdate(d){return `${d.getMonth()+1}/${d.getDate()}`}
function buildWeekSelect(){let n=state.race.weekCount||+$('weeks').value||12;$('weekSel').innerHTML='';for(let i=0;i<=n;i++){let o=document.createElement('option');o.value=i;o.textContent=i===0?'RACE WEEK':`D-${i}주`;if(i===current)o.selected=true;$('weekSel').append(o)}}
function defaults(){return DAY.map((_,i)=>({type:i===0?'휴식':[1,3,4].includes(i)?'조깅':'선택',amount:'',pace:'',memo:'',extra:[]}))}
function renderWeek(){let mon=mondayOfWeek(current),w=state.weeks[current]||{days:defaults(),focus:''};if(mon){let sun=new Date(mon);sun.setDate(mon.getDate()+6);$('weekDates').textContent=`${current===0?'RACE WEEK':`D-${current}주`} · ${fdate(mon)} ~ ${fdate(sun)}`}else $('weekDates').textContent='대회 날짜를 먼저 설정하세요.';$('days').innerHTML=w.days.map((d,i)=>dayHtml(d,i)).join('');$('focus').value=w.focus||''}
function options(sel){return ['선택',...TRAININGS].map(x=>`<option ${x===sel?'selected':''}>${x}</option>`).join('')} function dayHtml(d,i){return `<div class="day" data-i="${i}"><div class="dayname">${DAY[i]}</div><select class="type">${options(d.type)}</select><input class="amount" value="${esc(d.amount)}" placeholder="거리/시간/횟수"><input class="pace" value="${esc(d.pace)}" placeholder="페이스"><input class="memo" value="${esc(d.memo)}" placeholder="회복·보강·메모"><button class="add" title="복합훈련 추가">＋</button></div>${(d.extra||[]).map((e,j)=>`<div class="day extra" data-i="${i}" data-j="${j}"><div></div><select class="etype">${options(e.type)}</select><input class="eamount" value="${esc(e.amount)}" placeholder="거리/시간"><input class="epace" value="${esc(e.pace)}" placeholder="페이스"><input class="ememo" value="${esc(e.memo)}" placeholder="추가 훈련"><button class="del">×</button></div>`).join('')}`}
function esc(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))} function collect(){let w={days:defaults(),focus:$('focus').value};document.querySelectorAll('#days>.day:not(.extra)').forEach(el=>{let i=+el.dataset.i;w.days[i]={type:el.querySelector('.type').value,amount:el.querySelector('.amount').value,pace:el.querySelector('.pace').value,memo:el.querySelector('.memo').value,extra:[]}});document.querySelectorAll('#days>.extra').forEach(el=>{let i=+el.dataset.i;w.days[i].extra.push({type:el.querySelector('.etype').value,amount:el.querySelector('.eamount').value,pace:el.querySelector('.epace').value,memo:el.querySelector('.ememo').value})});return w}
function D(type,amount='',pace='',memo='',extra=[]){return{type,amount,pace,memo,extra}}
function autoFix(){if(!state.race.vd)return alert('먼저 10K PB를 입력하고 대회·훈련 기준 계산을 눌러주세요.');let r=state.race,k=r.k,mp=r.mPace,t=r.t,goal=r.goal||r.avg;
 state.weeks[3]={focus:'마지막 긴 T계열 지속 자극 + 마지막 마라톤 특이적 장거리 자극',days:[D('휴식'),D('조깅','',range(k+60,k+80)),D('2000m × 3','2000m × 3',range(k+3,k+8),'회복 400m 조깅 · 품질거리 6.0km'),D('조깅'),D('조깅'),D('E Easy Run','40~50분',range(k+60,k+80),'스트라이드 4~6회 선택'),D('24~26km Progressive + MP Finish','24~26km',`4km ${range(k+55,k+65)} / 10km ${range(k+45,k+50)} / 4km ${range(k+33,k+38)} / 마지막 6~8km ${paceFmt(mp)}`,'마지막 MP 추가 빌드업 금지')]};
 state.weeks[2]={focus:'T 능력 유지 + 훈련량 감소 + 레이스 운영 점검',days:[D('휴식'),D('조깅'),D('1600m × 3','1600m × 3',range(k+5,k+10),'회복 400m 조깅 · 품질거리 4.8km'),D('조깅'),D('조깅'),D('E Easy Run','30~40분',range(k+65,k+85),'또는 휴식'),D('Half 21.1km 통제주','21.1km',`개인 MP 부근 ${paceFmt(mp)}`,`PB 도전 금지 · 레이스화/젤/급수/운영 점검 · Half 기준 ${secFmt(goal/2-50)}`)]};
 state.weeks[1]={focus:'T 능력 유지 + 피로 제거',days:[D('휴식'),D('조깅'),D('1000m × 4','1000m × 4',range(k,k+5),'회복 400m 조깅 · 품질거리 4.0km'),D('조깅'),D('조깅'),D('E Easy Run','30~40분',range(k+65,k+85),'스트라이드 4회 선택'),D('12~14km Easy + MP 1~2km','12~14km',`대부분 ${range(k+60,k+80)} / 중·후반 MP ${paceFmt(mp)}`,'MP는 1~2km만')]};
 state.weeks[0]={focus:'RACE WEEK FIX · JD → 조깅 → 25분주 → 휴식 → 레이스',days:[D('휴식'),D('E Easy Run','40분 이내'),D('JACK DANIELS (E3.2k + T1200/E2분×4 + E3.2k)','E3.2km + (T1200m+E2분)×4 + E3.2km',paceFmt(t),'T Pace = 10K PB → VDOT'),D('E Easy Run','40분 이내'),D('25분주 + 1600m','20분 + 200m 회복 + 1600m',`20분 ${paceFmt(k+40)} / 1600m ${paceFmt(k)}`,'200m 회복'),D('완전 휴식'),D('FULL MARATHON','42.195km',paceFmt(mp),'RACE')]};save();current=3;buildWeekSelect();renderWeek();renderSchedule();alert('D-3주 · D-2주 · D-1주 · RACE WEEK FIX가 자동 입력되었습니다.')}
function txt(d){let one=[d.type,d.amount,d.pace,d.memo].filter(Boolean).join(' · ');let ex=(d.extra||[]).map(e=>[e.type,e.amount,e.pace,e.memo].filter(Boolean).join(' · '));return [one,...ex].filter(Boolean).join(' + ')}
function renderSchedule(){let n=state.race.weekCount||12,rows=[];for(let i=n;i>=0;i--){let mon=mondayOfWeek(i),w=state.weeks[i]||{days:defaults(),focus:''};rows.push({i,mon,w})}let groups={};rows.forEach(x=>{let key=x.mon?`${x.mon.getFullYear()}-${String(x.mon.getMonth()+1).padStart(2,'0')}`:'미설정';(groups[key]??=[]).push(x)});let keys=Object.keys(groups);if(!currentMonth)currentMonth=keys[0];let use=view==='month'?[currentMonth]:keys;$('schedule').innerHTML=use.map(k=>`<div class="monthTitle">${k==='미설정'?'날짜 미설정':k.replace('-','년 ')+'월'}</div><div class="schedule-wrap">${table(groups[k])}</div>`).join('')}
function table(rows){return `<table class="schedule-table"><thead><tr><th>주차</th><th>기간</th>${DAY.map((d,i)=>`<th class="${i===5?'sat':i===6?'sun':''}">${d}</th>`).join('')}<th>주간 핵심 포인트</th></tr></thead><tbody>${rows.map(x=>{let sun=x.mon?new Date(x.mon):null;if(sun)sun.setDate(sun.getDate()+6);return `<tr><td class="weektitle">${x.i===0?'RACE WEEK':`D-${x.i}주`}</td><td>${x.mon?fdate(x.mon)+'~'+fdate(sun):'-'}</td>${x.w.days.map((d,i)=>`<td class="${i===5?'sat':i===6?'sun':''}">${esc(txt(d))}</td>`).join('')}<td>${esc(x.w.focus||'')}</td></tr>`}).join('')}</tbody></table>`}
function monthKeys(){let n=state.race.weekCount||12,s=new Set;for(let i=n;i>=0;i--){let d=mondayOfWeek(i);if(d)s.add(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}return [...s]}
function exportXls(){let n=state.race.weekCount||12,html=`<html><head><meta charset="utf-8"></head><body><table border="1"><tr><th>주차</th><th>기간</th>${DAY.map(d=>`<th>${d}</th>`).join('')}<th>주간 핵심 포인트</th></tr>`;for(let i=n;i>=0;i--){let m=mondayOfWeek(i),s=m?new Date(m):null;if(s)s.setDate(s.getDate()+6);let w=state.weeks[i]||{days:defaults(),focus:''};html+=`<tr><td>${i===0?'RACE WEEK':`D-${i}주`}</td><td>${m?fdate(m)+'~'+fdate(s):''}</td>${w.days.map(d=>`<td>${esc(txt(d))}</td>`).join('')}<td>${esc(w.focus||'')}</td></tr>`}html+='</table></body></html>';download(new Blob([html],{type:'application/vnd.ms-excel'}),safeName()+'.xls')}
function png(){let keys=monthKeys();if(!currentMonth)currentMonth=keys[0];let n=state.race.weekCount||12,rows=[];for(let i=n;i>=0;i--){let m=mondayOfWeek(i);if(m&&`${m.getFullYear()}-${String(m.getMonth()+1).padStart(2,'0')}`===currentMonth)rows.push({i,mon:m,w:state.weeks[i]||{days:defaults(),focus:''}})}let W=1800,rowH=150,H=190+rows.length*rowH,cv=document.createElement('canvas');cv.width=W;cv.height=H;let c=cv.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,W,H);c.fillStyle='#0b2d63';c.fillRect(0,0,W,120);c.fillStyle='#fff';c.font='bold 38px sans-serif';c.fillText(`${state.race.name||'마라톤'} 훈련 스케줄`,35,52);c.font='24px sans-serif';c.fillText(`${currentMonth.replace('-','년 ')}월 · 평균 예상 ${state.race.avg?secFmt(state.race.avg):'-'} · VDOT M ${state.race.mPace?paceFmt(state.race.mPace):'-'}`,35,92);let widths=[110,150,175,175,175,175,175,175,175,315],x=[0];widths.forEach(v=>x.push(x[x.length-1]+v));c.font='bold 19px sans-serif';c.textAlign='center';['주차','기간',...DAY,'주간 핵심 포인트'].forEach((t,j)=>{c.fillStyle='#eaf1f8';c.fillRect(x[j],120,widths[j],70);c.strokeStyle='#9aa9ba';c.strokeRect(x[j],120,widths[j],70);c.fillStyle='#172033';c.fillText(t,x[j]+widths[j]/2,163)});rows.forEach((r,ri)=>{let y=190+ri*rowH,s=new Date(r.mon);s.setDate(s.getDate()+6);let vals=[r.i===0?'RACE WEEK':`D-${r.i}주`,`${fdate(r.mon)}~${fdate(s)}`,...r.w.days.map(txt),r.w.focus||''];vals.forEach((t,j)=>{c.fillStyle=j===8?'#fff2ed':j===7?'#eef8ff':'#fff';c.fillRect(x[j],y,widths[j],rowH);c.strokeStyle='#b5c0cd';c.strokeRect(x[j],y,widths[j],rowH);c.fillStyle='#172033';c.font=(j===0?'bold ':'')+'17px sans-serif';wrap(c,t,x[j]+8,y+30,widths[j]-16,24,5)})});cv.toBlob(b=>download(b,`${safeName()}_${currentMonth}.png`))}
function wrap(c,text,x,y,w,lh,max){c.textAlign='left';let chars=[...String(text||'')],line='',lines=[];for(let ch of chars){let test=line+ch;if(c.measureText(test).width>w){lines.push(line);line=ch}else line=test}if(line)lines.push(line);lines.slice(0,max).forEach((l,i)=>c.fillText(l,x,y+i*lh))}function safeName(){return (state.race.name||'marathon_schedule').replace(/[\\/:*?"<>|]/g,'_')} function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
$('calc').onclick=calculate;$('autoFix').onclick=autoFix;$('weekSel').onchange=e=>{state.weeks[current]=collect();save();current=+e.target.value;renderWeek()};$('prevW').onclick=()=>{if(current>0){state.weeks[current]=collect();save();current--;buildWeekSelect();renderWeek()}};$('nextW').onclick=()=>{let n=state.race.weekCount||12;if(current<n){state.weeks[current]=collect();save();current++;buildWeekSelect();renderWeek()}};$('days').onclick=e=>{if(e.target.classList.contains('add')){let w=collect(),i=+e.target.closest('.day').dataset.i;w.days[i].extra.push({type:'선택',amount:'',pace:'',memo:''});state.weeks[current]=w;renderWeek()}if(e.target.classList.contains('del')){let w=collect(),el=e.target.closest('.extra');w.days[+el.dataset.i].extra.splice(+el.dataset.j,1);state.weeks[current]=w;renderWeek()}};$('saveWeek').onclick=()=>{state.weeks[current]=collect();save();renderSchedule();alert(`${current===0?'RACE WEEK':`D-${current}주`} 저장 완료`)};$('copyPrev').onclick=()=>{let src=state.weeks[current+1];if(!src)return alert('앞선 주차에 저장된 구성이 없습니다.');state.weeks[current]=JSON.parse(JSON.stringify(src));save();renderWeek()};$('allView').onclick=()=>{view='all';renderSchedule()};$('monthView').onclick=()=>{let ks=monthKeys();if(!ks.length)return;let pick=prompt('볼 월을 입력하세요.\n'+ks.join(' / '),currentMonth||ks[0]);if(ks.includes(pick)){currentMonth=pick;view='month';renderSchedule()}};$('pngBtn').onclick=()=>{let ks=monthKeys();if(!ks.length)return alert('대회 날짜를 먼저 설정하세요.');if(view!=='month'){let p=prompt('PNG로 저장할 월을 선택하세요.\n'+ks.join(' / '),ks[0]);if(!ks.includes(p))return;currentMonth=p}png()};$('xlsBtn').onclick=exportXls;$('printBtn').onclick=()=>window.print();
if(state.race.name){$('raceName').value=state.race.name;$('raceDate').value=state.race.date||'';$('sex').value=state.race.sex||'male';$('tenk').value=state.race.ten?`${Math.floor(state.race.ten/60)}${String(state.race.ten%60).padStart(2,'0')}`:'';$('weeks').value=state.race.weekCount||12;if(state.race.goal){let g=state.race.goal;$('goalFull').value=`${Math.floor(g/3600)}${String(Math.floor(g%3600/60)).padStart(2,'0')}${String(Math.round(g%60)).padStart(2,'0')}`}}renderMetrics();buildWeekSelect();renderWeek();renderSchedule();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
